# Lesson 7: Matrix Math and Numpy Refresher

Numpy is a library that provides fast operations in Python efficiently



In [1]:
import numpy as np

Data types:

    * ndarray objects (most common)
    * scalars
    * vectors
    * matrices
    * tensors

ndarray objects can store any number of dimensions, any number types, any data types. Every iten in the ndarray must have the same number type.



Number types:

    * uint8
    * int8
    * uint16
    * ...
    
   

### 1. Scalars

In [2]:
# create a Numpy array that holds a scalar
a = np.array(5)

In [5]:
a.shape

()

( ) indicates 0 dimensions, because ```a``` is a ndarray which holds a scalar.

In [7]:
x = a + 3
x

8

In [10]:
type(a)

numpy.ndarray

In [11]:
type(x)

numpy.int64

In [12]:
x.shape

()

( ) here because x is a scalar. If x is a integer, x.shape will raise an error.

In [13]:
x = 10
x.shape

AttributeError: 'int' object has no attribute 'shape'

### 2. Vectors

In [21]:
# create a vector by passing a Python list
v = np.array([1, 2, 3, 4, 5, 6, 7])

In [22]:
v.shape

(7,)

In [23]:
x = v[1]
x

2

We can only use slicing and indexing.

[documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

In [24]:
v[1:]

array([2, 3, 4, 5, 6, 7])

In [26]:
v[0:5:2]

array([1, 3, 5])

### 3. Matrices

In [27]:
# create a matrix by passing a list of lists
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [28]:
m.shape

(3, 3)

In [29]:
m[1][2]

6

In [30]:
m[1, 2]

6

### 4. Tensors

Tensors have more dimensions. It is basically like a combination of vectors and matrices.

In [37]:
# create a tensor
t = np.array([
    [
        [
            [1],
            [2]
        ],
        [
            [3],
            [4]
        ],
        [
            [5],
            [6]
        ]
    ],
    [
        [
            [7],
            [8]
        ],
        [
            [9],
            [10]
        ],
        [
            [11],
            [12]
        ]
    ],
    [
        [
            [13],
            [14]
        ],
        [
            [15],
            [16]
        ],
        [
            [17],
            [18]
        ]
    ]
])

In [38]:
t.shape

(3, 3, 2, 1)

(3, 3, 2, 1) indicates, we can see ```t``` has a 3x3 structure A like that:
```
[
    [
        ...
    ]
],
```

Inside each structure A, it has a 2x1 structure B like:
```
[x],
[y]
```

That's where (3, 3, 2, 1) comes from.

In [39]:
t[2][1][1][0]

16

In [40]:
t[2, 1, 1, 0]

16

In [41]:
# create another tensor
# create a tensor
t2 = np.array([
    [
        [
            [1, 1.5],
            [2, 2.5]
        ],
        [
            [3, 3.5],
            [4, 4.5]
        ],
        [
            [5, 5.5],
            [6, 6.5]
        ]
    ],
    [
        [
            [7, 7.5],
            [8, 8.5]
        ],
        [
            [9, 9.5],
            [10, 10.5]
        ],
        [
            [11, 11.5],
            [12, 12.5]
        ]
    ],
    [
        [
            [13, 13.5],
            [14, 14.5]
        ],
        [
            [15, 15.5],
            [16, 16.5]
        ],
        [
            [17, 17.5],
            [17, 18.5]
        ]
    ]
])

What is the shape of ```t2``` ?

In [42]:
t2.shape

(3, 3, 2, 2)

In [43]:
t2[2][0][1][0]

14.0

In [44]:
type(t2)

numpy.ndarray

### 5. Changing shapes

Change shape without changing its contents.

Call ```.reshape(.)``` function.

In [47]:
v = np.array([1, 2, 3, 4])
print(v.shape)

x = v.reshape(1, 4)
print(x.shape)
print(x)

x = v.reshape(4, 1)
print(x.shape)
print(x)

(4,)
(1, 4)
[[1 2 3 4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]


In [48]:
# use special slicing instead of calling reshape
x = v[None, :]  # add a new associate dimension of size 1 as the first dimension
print(x.shape)
print(x)

x = v[:, None]  # add a new associate dimension of size 1 as the second dimension
print(x.shape)
print(x)

(1, 4)
[[1 2 3 4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]


### 6. Element-wise operations

In [52]:
# do matrix operations like scalar
m = np.array([
    [1, 2],
    [3, 4]
])
print(m + 2)
print(m / 10)

[[3 4]
 [5 6]]
[[0.1 0.2]
 [0.3 0.4]]


In [58]:
# element-wise matrices operations
# 2 matrices must have same shapes
m1 = np.array([
    [1, 2],
    [3, 4]
])
m2 = np.array([
    [6, 7],
    [8, 9]
])
print(m1 + m2)
print(m1 * m2)

[[ 7  9]
 [11 13]]
[[ 6 14]
 [24 36]]


In [55]:
# same works for vectors
values = list([1, 2, 3, 4, 5])
v = np.array(values) + 5
print(v)

# we can also call built-in NumPy functions
v = np.add(values, 5)
print(v)

[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [57]:
# reset m to all 0s
print(m)
m_reset = m * 0
print(m_reset)

[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


### 7. Matrix Product  (Dot Product)

[Dot product](https://en.wikipedia.org/wiki/Dot_product)

$M_1 \cdot M_2$

When multiplying, data in $M_1$ is arranged as **rows**, data in $M_2$ is arranged as **columns**.

**7.1 Requirement:**

\# of columns in $M_1$ must == \# of rows in $M_2$

example: 

$M_1$ is shape of (m, n)

$M_2$ is shape of (p, q)

Then, m must == p

Shape of $M_1 \cdot M_2$ is (m, q)

**7.2 Attribute:**

Commutative rule does not hold: $$M_1 \cdot M_2 \neq M_2 \cdot M_1$$

**7.3 NumPy element-wise matrix multiplication**

Call ```np.multiply(.)``` or use ```*``` operator.


In [60]:
import numpy as np

m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

res = m * 10
print(res)

ans = np.multiply(m, 10)
print(ans)

print(m * ans)

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[ 10  40  90]
 [160 250 360]]


**7.4 Matrix Product**

Call ```np.matmul(a, b)``` or ```np.dot(a, b)``` or ```@```

```dot``` and ```matmul``` produce the same result if the matrices are two dimensional.

@ calls ```matmul``` function, not ```dot```


In [61]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(a.shape, b.shape)

(2, 4) (4, 3)


In [64]:
c = np.matmul(a, b)
print(c.shape)
print(c)

d = np.dot(a, b)
print(d.shape)
print(d)

e = a @ b
print(e.shape)
print(e)

(2, 3)
[[ 70  80  90]
 [158 184 210]]
(2, 3)
[[ 70  80  90]
 [158 184 210]]
(2, 3)
[[ 70  80  90]
 [158 184 210]]


When opearting on other data shapes in more dimensions, ```matmul``` and ```dot``` may produce different results.

From the documentation:

```matmul``` differs from ```dot``` in 2 ways:
    
* Multiplication by scalars is not allows.
* Stacks of matrices are broadcast together as if the matrices were elements.

[Reference](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication)

### 8. Matrix Transposes

**2 important attributes:**

1. Transposed matrix has a new shape if the original matrix is not square. (e.g. (2, 4) -> (4, 2))

2. If original matrix is arranged as rows, then transposed matrix is arranged as columns, vice versa. Because during matrix product, we are dealing with **rows** in the first matrix, and dealing with **columns** in the second matrix.


For the 2nd attribute, if 2 original matrices are arranged as rows, then we can transpose 1 matrix then do product multiplication.

However, if 2 original matrices are arranged as columns, then neither options work.


*Note: arranged as rows means a row indicates 1 instance. Opposite for arranged as columns.*

**Summary: we can safely use a transpose in a matrix multiplication if the data in both of original matrices is arranged as rows. i.e. 1 instance per row.**



**8.1 Transpose**

Call ```np.transpose(m)``` or just call ```m.T```.

Both ways are efficient.

In [65]:
import numpy as np

m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.transpose(m))
print(m.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


A matrix and its transpose **share the same memory**. Because NumPy doesn't allocate a new memory when calling ```m.T``` or ```np.transpose(m)```. When we modify ```m```, we are also modifying ```m.T```.

If we want to find product of 2 matrices $M_1$, $M_2$ of shape (1, 4) and (3, 4), there are 2 ways:

1. transpose the second matrix, i.e. np.matmul($M_1$, $M_2.T$) -> (1, 3)

2. transpse the first matrix, then swap the order, i.e. np.matmul($M_2$, $M_1.T$) -> (3, 1)

2 results, (1, 3) and (3, 1), contain the same values but are transposes of each other.


### 9. Quiz

Complete the cell below:

In [67]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = None
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = None

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = None

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    pass


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    pass
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    pass


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: None
Input minus min: None
Input  Array: None
Multiply 1:
None
Multiply 2:
None
Multiply 3:
None
Mean == None


My answer:


In [78]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(inputs)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1] != m2.shape[0] and m2.shape[1] != m1.shape[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    return np.matmul(m1, m2) if m1.shape[1] == m2.shape[0] else np.matmul(m2, m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
